# Generated by Django 5.1.6 on 2025-02-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('recommended_for', models.CharField(choices=[('family', 'Família'), ('adventurer', 'Aventureiro'), ('couples', 'Casais'), ('seniors', 'Idosos'), ('nature_lovers', 'Amantes da Natureza')], default='family', max_length=20)),
            ],
        ),
    ]
